source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.4'

gem 'rails', '~> 6.1.4'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 5.0'
gem 'sassc-rails', '~> 2.1.2'
gem 'webpacker', '~> 5.4'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem "redis", '~> 4.2', '>= 4.2.5', :require => ["redis", "redis/connection/hiredis"]
gem "hiredis"
gem 'cable_ready', '~> 4.5'
# gem 'bcrypt', '~> 3.1.7'
gem 'image_processing', '~> 1.2'

# Project Specific
gem 'active_decorator'
gem 'aws-sdk-s3', '~> 1.88'
gem 'aws-sdk-cloudfront', '~> 1.48'
gem 'aws-sdk-ses', '~> 1.37'
gem 'caxlsx', '~> 3.0', '>= 3.0.4'
gem 'caxlsx_rails'
gem 'chartkick'
gem 'faraday', '~> 1.4', '>= 1.4.2'
gem 'net-http'
gem 'geocoder'
gem 'groupdate'
gem 'kramdown', '~> 2.3'
gem 'kramdown-parser-gfm'
gem 'lockbox'
gem 'mini_magick', '~> 4.11'
gem 'newrelic_rpm'
gem "devise"
gem 'exception_notification'
gem 'pg_search'
gem 'pagy', '~> 4.11'
gem 'nokogiri'
gem 'rack-cors'
gem 'stimulus_reflex', '~> 3.4', '>= 3.4.1'
gem 'libxml-ruby'
gem 'remove_emoji'
gem 'rails_autoscale_agent'

gem 'bootsnap', '>= 1.4.4', require: false

group :development, :test do
  # Call 'byebug' to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'factory_bot_rails', '~> 6.1'
  gem 'guard-rspec', require: false
  gem 'pry'
  gem 'rspec-rails', '~> 4.0', '>= 4.0.2'
  gem 'shoulda-matchers', '~> 4.5', '>= 4.5.1'
  gem 'standard'
  gem 'squasher'
end

group :development do
  gem 'better_errors'
  gem 'brakeman'
  gem 'bullet'
  gem 'rails-erd'
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.3', '>= 2.3.1'
  gem 'rails-footnotes', '~> 5.0'
end

group :test do
  gem 'capybara', '~> 3.35'
  gem 'database_rewinder'
  gem 'ffaker'
  gem "n_plus_one_control"
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
