source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.4"
gem "sassc-rails"
gem "rails", "~> 7.0", ">= 7.0.2.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

gem "jbuilder"
gem "redis", "~> 4.2", ">= 4.2.5", :require => ["redis", "redis/connection/hiredis"]
gem "hiredis"
gem "cable_ready", ">= 5.0.0.pre"
gem "image_processing", "~> 1.2"

# Rails 7
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
# gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"
# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"
gem "stimulus_reflex", "= 3.5.0.pre9"
gem "jsbundling-rails", "~> 1.0"


# Project Specific
gem "active_decorator"
gem "aws-sdk-s3", "~> 1.88"
gem "aws-sdk-cloudfront", "~> 1.48"
gem "aws-sdk-ses", "~> 1.37"
gem "caxlsx", "~> 3.0", ">= 3.0.4"
gem "caxlsx_rails"
gem "chartkick"
gem "faraday", "~> 1.4", ">= 1.4.2"
gem "net-http"
gem "geocoder"
gem "groupdate"
gem "kramdown", "~> 2.3"
gem "kramdown-parser-gfm"
gem "lockbox"
gem "mini_magick", "~> 4.11"
gem "newrelic_rpm"
gem "devise"
gem "exception_notification"
gem "pg_search"
gem "pagy", "~> 4.11"
gem "nokogiri"
gem "rack-cors"
gem "libxml-ruby"
gem "remove_emoji"
gem "rails_autoscale_agent"


group :development, :test do
  # Call "byebug" to stop execution and get a debugger console
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "factory_bot_rails", "~> 6.1"
  gem "guard-rspec", require: false
  gem "pry"
  gem "rspec-rails", "~> 4.0", ">= 4.0.2"
  gem "shoulda-matchers", "~> 4.5", ">= 4.5.1"
  gem "standard"
  gem "squasher"
end

group :development do
# Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  gem "rack-mini-profiler"
  gem "better_errors"
  gem "brakeman"
  gem "bullet"
  gem "rails-erd"
  gem "listen", "~> 3.3"
  #gem "rails-footnotes"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem "database_rewinder"
  gem "ffaker"
  gem "n_plus_one_control"
end
